name: Blog CI

on:
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: use node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install Deps
        run: npm i

      - name: setup environments
        run: |
          echo "VITE_BASE_URL=${{ secrets.VITE_BASE_URL }}" >> .env.production
          echo "VITE_ENC_KEY=${{ secrets.VITE_ENC_KEY }}" >> .env.production

      - name: list dir
        run: |
          ls -la

      - name: build for production
        run: npm run build --if-present

      - name: start server
        run: pm2 restart blog-f
