name: Blog CI

on:
  release:
    branches: ['main']
    types:
      - 'published'

jobs:
  clean-up:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
      - name: clean dist dir
        run: |
          rm -rf dist

      - name: list dir
      - run: |
          ls -la

  install-deps-and-build:
    needs: clean-up

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install Deps
        run: npm i

      - name: Setup Environmen Variables
        run: |
          echo "VITE_BASE_URL=${{ secrets.VITE_BASE_URL }}" >> .env.production
          echo "VITE_ENC_KEY=${{ secrets.VITE_ENC_KEY }}" >> .env.production

      - name: Listing Directory
        run: |
          echo "Successfully Setup Env"
          ls -la

      - name: Start building
        run: npm run build

      - name: Start server | Restart Serve
        run: pm2 serve ./dist 8000
