name: Blog Backend CI

on:
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install Deps
        run: npm i

      - name: Setup .env
        run: |
          echo "VITE_BASE_URL=${{ secrets.VITE_BASE_URL }}" >> .env
          echo "VITE_ENC_KEY=${{ secrets.VITE_ENC_KEY }}" >> .env

      - name: List Dirs
        run: |
          echo "Successfully Setup Env"
          ls -la

      - name: Transpile Code
        run: npm run build

      - name: Start the server
        run: npm run start

      - name: Successfully
        run: |
          echo "Server Updated!"
