name: Draft Releaser

on:
  release:
    branch: ['main']
    types:
      - 'published'
    tags:
      - 'v*'

  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  contents: read

jobs:
  draft-release:
    permissions:
      contents: write
      pull-requests: write

    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          template: |
            ## What's changed

            $CHANGED
