name: Draft Releaser

on:
  pull_request:
    branches: ['main']
    tags:
      - 'v*'

permissions:
  contents: read

jobs:
  draft-release:
    permissions:
      contents: write
      pull-requests: write

    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
